INSERT INTO data VALUES ('item 0');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 1');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 2');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 3');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 4');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 5');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 6');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 7');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 8');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 9');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 10');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 11');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 12');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 13');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 14');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 15');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 16');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 17');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 18');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 19');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 20');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 21');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 22');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 23');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 24');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 25');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 26');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 27');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 28');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 29');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 30');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 31');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 32');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 33');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 34');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 35');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 36');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 37');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 38');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 39');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 40');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 41');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 42');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 43');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 44');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 45');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 46');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 47');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 48');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 49');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 50');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 51');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 52');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 53');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 54');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 55');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 56');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 57');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 58');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 59');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 60');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 61');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 62');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 63');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 64');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 65');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 66');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 67');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 68');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 69');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 70');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 71');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 72');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 73');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 74');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 75');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 76');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 77');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 78');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 79');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 80');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 81');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 82');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 83');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 84');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 85');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 86');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 87');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 88');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 89');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 90');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 91');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 92');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 93');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 94');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 95');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 96');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 97');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 98');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 99');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 100');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 101');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 102');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 103');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 104');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 105');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 106');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 107');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 108');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 109');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 110');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 111');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 112');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 113');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 114');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 115');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 116');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 117');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 118');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 119');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 120');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 121');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 122');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 123');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 124');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 125');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 126');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 127');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 128');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 129');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 130');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 131');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 132');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 133');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 134');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 135');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 136');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 137');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 138');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 139');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 140');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 141');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 142');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 143');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 144');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 145');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 146');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 147');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 148');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 149');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 150');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 151');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 152');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 153');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 154');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 155');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 156');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 157');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 158');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 159');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 160');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 161');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 162');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 163');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 164');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 165');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 166');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 167');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 168');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 169');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 170');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 171');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 172');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 173');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 174');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 175');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 176');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 177');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 178');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 179');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 180');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 181');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 182');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 183');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 184');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 185');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 186');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 187');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 188');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 189');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 190');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 191');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 192');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 193');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 194');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 195');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 196');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 197');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 198');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 199');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 200');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 201');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 202');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 203');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 204');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 205');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 206');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 207');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 208');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 209');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 210');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 211');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 212');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 213');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 214');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 215');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 216');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 217');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 218');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 219');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 220');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 221');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 222');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 223');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 224');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 225');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 226');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 227');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 228');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 229');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 230');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 231');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 232');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 233');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 234');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 235');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 236');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 237');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 238');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 239');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 240');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 241');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 242');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 243');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 244');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 245');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 246');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 247');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 248');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 249');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 250');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 251');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 252');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 253');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 254');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 255');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 256');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 257');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 258');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 259');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 260');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 261');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 262');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 263');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 264');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 265');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 266');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 267');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 268');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 269');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 270');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 271');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 272');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 273');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 274');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 275');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 276');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 277');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 278');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 279');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 280');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 281');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 282');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 283');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 284');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 285');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 286');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 287');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 288');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 289');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 290');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 291');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 292');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 293');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 294');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 295');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 296');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 297');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 298');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 299');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 300');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 301');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 302');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 303');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 304');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 305');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 306');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 307');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 308');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 309');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 310');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 311');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 312');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 313');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 314');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 315');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 316');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 317');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 318');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 319');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 320');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 321');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 322');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 323');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 324');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 325');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 326');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 327');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 328');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 329');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 330');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 331');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 332');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 333');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 334');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 335');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 336');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 337');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 338');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 339');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 340');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 341');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 342');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 343');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 344');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 345');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 346');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 347');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 348');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 349');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 350');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 351');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 352');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 353');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 354');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 355');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 356');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 357');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 358');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 359');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 360');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 361');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 362');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 363');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 364');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 365');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 366');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 367');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 368');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 369');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 370');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 371');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 372');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 373');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 374');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 375');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 376');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 377');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 378');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 379');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 380');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 381');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 382');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 383');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 384');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 385');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 386');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 387');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 388');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 389');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 390');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 391');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 392');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 393');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 394');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 395');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 396');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 397');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 398');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 399');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 400');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 401');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 402');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 403');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 404');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 405');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 406');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 407');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 408');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 409');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 410');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 411');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 412');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 413');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 414');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 415');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 416');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 417');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 418');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 419');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 420');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 421');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 422');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 423');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 424');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 425');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 426');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 427');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 428');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 429');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 430');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 431');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 432');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 433');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 434');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 435');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 436');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 437');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 438');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 439');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 440');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 441');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 442');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 443');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 444');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 445');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 446');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 447');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 448');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 449');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 450');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 451');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 452');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 453');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 454');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 455');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 456');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 457');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 458');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 459');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 460');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 461');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 462');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 463');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 464');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 465');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 466');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 467');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 468');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 469');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 470');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 471');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 472');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 473');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 474');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 475');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 476');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 477');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 478');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 479');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 480');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 481');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 482');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 483');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 484');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 485');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 486');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 487');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 488');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 489');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 490');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 491');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 492');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 493');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 494');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 495');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 496');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 497');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 498');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 499');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 500');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 501');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 502');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 503');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 504');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 505');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 506');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 507');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 508');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 509');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 510');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 511');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 512');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 513');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 514');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 515');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 516');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 517');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 518');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 519');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 520');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 521');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 522');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 523');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 524');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 525');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 526');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 527');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 528');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 529');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 530');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 531');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 532');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 533');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 534');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 535');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 536');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 537');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 538');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 539');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 540');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 541');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 542');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 543');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 544');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 545');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 546');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 547');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 548');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 549');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 550');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 551');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 552');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 553');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 554');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 555');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 556');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 557');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 558');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 559');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 560');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 561');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 562');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 563');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 564');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 565');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 566');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 567');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 568');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 569');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 570');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 571');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 572');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 573');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 574');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 575');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 576');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 577');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 578');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 579');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 580');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 581');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 582');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 583');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 584');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 585');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 586');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 587');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 588');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 589');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 590');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 591');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 592');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 593');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 594');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 595');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 596');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 597');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 598');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 599');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 600');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 601');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 602');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 603');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 604');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 605');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 606');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 607');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 608');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 609');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 610');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 611');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 612');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 613');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 614');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 615');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 616');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 617');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 618');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 619');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 620');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 621');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 622');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 623');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 624');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 625');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 626');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 627');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 628');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 629');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 630');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 631');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 632');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 633');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 634');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 635');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 636');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 637');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 638');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 639');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 640');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 641');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 642');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 643');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 644');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 645');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 646');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 647');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 648');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 649');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 650');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 651');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 652');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 653');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 654');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 655');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 656');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 657');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 658');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 659');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 660');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 661');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 662');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 663');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 664');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 665');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 666');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 667');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 668');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 669');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 670');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 671');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 672');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 673');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 674');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 675');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 676');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 677');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 678');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 679');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 680');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 681');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 682');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 683');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 684');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 685');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 686');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 687');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 688');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 689');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 690');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 691');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 692');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 693');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 694');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 695');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 696');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 697');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 698');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 699');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 700');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 701');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 702');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 703');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 704');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 705');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 706');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 707');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 708');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 709');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 710');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 711');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 712');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 713');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 714');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 715');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 716');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 717');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 718');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 719');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 720');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 721');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 722');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 723');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 724');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 725');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 726');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 727');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 728');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 729');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 730');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 731');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 732');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 733');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 734');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 735');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 736');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 737');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 738');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 739');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 740');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 741');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 742');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 743');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 744');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 745');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 746');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 747');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 748');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 749');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 750');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 751');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 752');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 753');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 754');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 755');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 756');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 757');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 758');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 759');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 760');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 761');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 762');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 763');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 764');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 765');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 766');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 767');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 768');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 769');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 770');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 771');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 772');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 773');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 774');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 775');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 776');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 777');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 778');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 779');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 780');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 781');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 782');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 783');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 784');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 785');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 786');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 787');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 788');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 789');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 790');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 791');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 792');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 793');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 794');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 795');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 796');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 797');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 798');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 799');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 800');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 801');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 802');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 803');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 804');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 805');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 806');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 807');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 808');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 809');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 810');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 811');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 812');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 813');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 814');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 815');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 816');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 817');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 818');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 819');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 820');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 821');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 822');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 823');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 824');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 825');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 826');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 827');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 828');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 829');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 830');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 831');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 832');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 833');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 834');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 835');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 836');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 837');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 838');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 839');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 840');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 841');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 842');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 843');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 844');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 845');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 846');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 847');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 848');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 849');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 850');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 851');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 852');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 853');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 854');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 855');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 856');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 857');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 858');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 859');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 860');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 861');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 862');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 863');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 864');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 865');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 866');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 867');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 868');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 869');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 870');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 871');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 872');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 873');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 874');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 875');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 876');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 877');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 878');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 879');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 880');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 881');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 882');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 883');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 884');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 885');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 886');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 887');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 888');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 889');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 890');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 891');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 892');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 893');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 894');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 895');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 896');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 897');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 898');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 899');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 900');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 901');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 902');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 903');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 904');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 905');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 906');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 907');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 908');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 909');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 910');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 911');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 912');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 913');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 914');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 915');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 916');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 917');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 918');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 919');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 920');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 921');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 922');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 923');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 924');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 925');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 926');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 927');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 928');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 929');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 930');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 931');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 932');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 933');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 934');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 935');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 936');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 937');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 938');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 939');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 940');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 941');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 942');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 943');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 944');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 945');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 946');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 947');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 948');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 949');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 950');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 951');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 952');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 953');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 954');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 955');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 956');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 957');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 958');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 959');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 960');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 961');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 962');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 963');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 964');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 965');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 966');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 967');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 968');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 969');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 970');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 971');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 972');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 973');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 974');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 975');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 976');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 977');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 978');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 979');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 980');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 981');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 982');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 983');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 984');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 985');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 986');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 987');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 988');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 989');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 990');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 991');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 992');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 993');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 994');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 995');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 996');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 997');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 998');
SELECT pg_sleep(0.5);
INSERT INTO data VALUES ('item 999');
SELECT pg_sleep(0.5);
